# Generated by Django 5.2.17 on 2026-09-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='secteur',
            field=models.CharField(choices=[('I', 'informatique'), ('G', 'gestion')], max_length=80),
        ),
        migrations.AddConstraint(
            model_name='entreprise',
            constraint=models.UniqueConstraint(fields=('nom', 'ville'), name='nom_ville'),
        ),
    ]
