# Generated by Django 5.2.17 on 2026-09-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_alter_entreprise_secteur_entreprise_nom_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='nom',
            field=models.CharField(max_length=120),
        ),
    ]
