# Generated by Django 5.2.17 on 2026-10-03 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [  # noqa: RUF012
        ('stages', '0003_alter_entreprise_nom'),
    ]

    operations = [  # noqa: RUF012
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant_referent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('sexe', models.CharField(choices=[('F', 'Femme'), ('H', 'Homme')], max_length=80)),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'tuteur',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('sexe', models.CharField(choices=[('F', 'Femme'), ('H', 'Homme')], max_length=80)),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('matricule', models.CharField(max_length=150)),
                ('promotion', models.CharField(max_length=150)),
                ('competence', models.ManyToManyField(related_name='etudiants', to='stages.competence')),
            ],
            options={
                'verbose_name': 'etudiant',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nb_places', models.IntegerField()),
                ('competence', models.ManyToManyField(related_name='offre', to='stages.competence')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offres', to='stages.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('Depose', 'Depose'), ('Retenue', 'Retenue'), ('Refuse', 'Refuse')], max_length=150)),
                ('date_depot', models.DateField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='stages.etudiant')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='stages.offre')),
            ],
        ),
        migrations.CreateModel(
            name='Tuteur_entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('sexe', models.CharField(choices=[('F', 'Femme'), ('H', 'Homme')], max_length=80)),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tuteurs_entreprise', to='stages.entreprise')),
            ],
            options={
                'verbose_name': 'tuteur',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=150)),
                ('candidature', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stage', to='stages.candidature')),
                ('enseignant_referent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='stages.enseignant_referent')),
                ('tuteur_entreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='stages.tuteur_entreprise')),
            ],
        ),
        migrations.AddConstraint(
            model_name='candidature',
            constraint=models.UniqueConstraint(fields=('etudiant', 'offre'), name='offre_etudiant'),
        ),
    ]
