# Generated by Django 5.2.17 on 2026-10-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0004_competence_enseignant_referent_etudiant_offre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='promotion',
            field=models.IntegerField(),
        ),
    ]
