# Generated by Django 5.2.17 on 2026-10-04 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [  # noqa: RUF012
        ('stages', '0005_alter_etudiant_promotion'),
    ]

    operations = [  # noqa: RUF012
        migrations.RenameField(
            model_name='etudiant',
            old_name='competence',
            new_name='competences',
        ),
        migrations.RenameField(
            model_name='offre',
            old_name='competence',
            new_name='competences',
        ),
    ]
