# Generated by Django 5.2.17 on 2026-10-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0006_rename_competence_etudiant_competences_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enseignant_referent',
            options={'ordering': ['nom']},
        ),
    ]
