# Generated by Django 5.2.17 on 2026-10-09 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0007_alter_enseignant_referent_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enseignant_referent',
            new_name='EnseignantReferent',
        ),
        migrations.RenameModel(
            old_name='Tuteur_entreprise',
            new_name='TuteurEntreprise',
        ),
    ]
